name: "Test and build"

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  assertFormated:
    name: "AssertFormated"
    runs-on: macos-12
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2

      - name: "Run Lint"
        run: |
          brew install swiftformat
          swiftformat . --lint

  unit_tests:
    name: "Unit tests"
    runs-on: macos-12

    needs:
      - assertFormated

    steps:
      - uses: actions/checkout@v2

      - uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: |
            ${{ secrets.SWIFT_PROFILE_SSH_KEY }}
            ${{ secrets.SLIP_10_SSH_KEY }}

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "14.0.1"

      - name: "Run unit tests"
        run: |
          swift test

  # snapshot_tests:
  #   name: "Snapshot tests"
  #   runs-on: macos-12

  #   needs:
  #     - assertFormated

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: "Run snapshot tests"
  #       run: echo "Runing snapshot tests" # JUST A PLACEHOLDER, NEEDS TO BE REPLACED

  # ui_tests:
  #   name: "UI tests"
  #   runs-on: macos-12

  #   needs:
  #     - assertFormated

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: "Run UI tests"
  #       run: echo "Runing UI tests" # JUST A PLACEHOLDER, NEEDS TO BE REPLACED

  static_analysis:
    name: "SonarCloud"
    runs-on: ubuntu-latest

    continue-on-error: true

    needs:
      - unit_tests
      # - snapshot_tests
      # - ui_tests

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Run static analysis and Sonarcloud"
        run: echo "Hello World" # JUST A PLACEHOLDER, NEEDS TO BE REPLACED

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}